runtime: java
instance_class: F4

handlers:
  - url: /.*
    script: this field is required, but ignored

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9

service:
  springboot-appengine-test